[data]
desc = "Configuration for the data"
data_url = "https://raw.githubusercontent.com/ageron/handson-ml/master/"
target = "median_house_value"

[dev]
desc = "Configuration for the Dev environment"

[prod]
desc = "Configuration for the Prod environment"